### ISSUE TITLE
Why are you here?

### ISSUE THREAD

**Issue by oganm** [Jameswells96/zz_Wells_James#1]
Hi James, I see you are working here while we sent you an invitation so you can access your private repo. 

You also did not submit your work. Are you auditing the course or are you a real student?

You can see the invite [here](https://github.com/STAT540-UBC/zz_wells-james_STAT540_2018/invitations)

**Comment by Jameswells96** [comment]
Hi there,

I am in the course. The invitation I used must have not worked properly.

I have moved most of my files over to this new private repository and will make a new issue.

Thanks

**Comment by oganm** [comment]
Ok don't forget to open issues for homework submission next time. And while moving please don't remove these because I'll be looking here to grade.
